### ISSUE TITLE
Contribuição da comunidade

### ISSUE THREAD

**Issue by wellingtoncosta** [EscolaDeSaudePublica/coronavirusAPI#12]
Olá,

Primeiramente gostaria de parabenizar a iniciativa da Escola de Saúde Pública do nosso estado de desenvolver essa aplicação e também pelo código estar aberto aqui no GitHub. Muito bacana ver essas iniciativas open source nas entidades governamentais.

Eu gosto bastante de contribuir em projetos open source e gostaria de saber se o projeto está aberto para receber PRs da comunidade.

**Comment by uira** [comment]
A gente é que fica muito feliz com o reconhecimento! Nos motiva ainda mais... :D

Sobre receber PRs: É O QUE MAIS QUEREMOS.

Temos muitas limitações no setor público, e entendemos que o código aberto potencializa a colaboração em rede, assim como racionaliza e otimiza os recursos públicos. #VemPR

**Comment by wellingtoncosta** [comment]
Muito bacana, @uira. Achei os projetos muito bacana e espero poder contribuir de alguma forma muito em breve! :)

Abraço!
