### ISSUE TITLE
Colocar links dos Gráficos no README

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/coronavirusAPI#4]
Nos [Caminhos para os gráficos](https://github.com/EscolaDeSaudePublica/covid-19-graphics#caminhos-para-os-gr%C3%A1ficos)

/curva-epidemiologica: Gráfico em linhas que mostra o quantitativo de casos confirmados e óbitos.
/rosca-casos-por-municipio: Gráfico circular com cada caso confirmado por município
/tabela-casos-por-municipio: Tabela descritiva com cada caso por município
/casos-por-dia: Gráfico em Linha mostrando o quantitativo de novos casos por dia.

**Comment by ItaloRod** [comment]
Adicionado na Branch de Desenvolvimento . Inclui também um tutorial para servir a parte em Vue no Laravel
